/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FailedAccessibleTenantProfileAssignmentDTO;
import com.konfigthis.client.model.SuccessfulAccessibleTenantProfileAssignmentDTO;
import com.konfigthis.client.model.TenantCodeErrorDTO;
import com.konfigthis.client.model.UserIdErrorDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AccessibleTenantProfileAssignmentResponseDTO
 */
public class AccessibleTenantProfileAssignmentResponseDTOTest {
    private final AccessibleTenantProfileAssignmentResponseDTO model = new AccessibleTenantProfileAssignmentResponseDTO();

    /**
     * Model tests for AccessibleTenantProfileAssignmentResponseDTO
     */
    @Test
    public void testAccessibleTenantProfileAssignmentResponseDTO() {
        // TODO: test AccessibleTenantProfileAssignmentResponseDTO
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'badTenantCodes'
     */
    @Test
    public void badTenantCodesTest() {
        // TODO: test badTenantCodes
    }

    /**
     * Test the property 'badUserIds'
     */
    @Test
    public void badUserIdsTest() {
        // TODO: test badUserIds
    }

    /**
     * Test the property 'failedAssignments'
     */
    @Test
    public void failedAssignmentsTest() {
        // TODO: test failedAssignments
    }

    /**
     * Test the property 'successfulAssignments'
     */
    @Test
    public void successfulAssignmentsTest() {
        // TODO: test successfulAssignments
    }

}
