/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProfileAssignedForAccessibleTenantDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AllProfileAssignedForAccessibleTenantDTO
 */
public class AllProfileAssignedForAccessibleTenantDTOTest {
    private final AllProfileAssignedForAccessibleTenantDTO model = new AllProfileAssignedForAccessibleTenantDTO();

    /**
     * Model tests for AllProfileAssignedForAccessibleTenantDTO
     */
    @Test
    public void testAllProfileAssignedForAccessibleTenantDTO() {
        // TODO: test AllProfileAssignedForAccessibleTenantDTO
    }

    /**
     * Test the property 'assignedProfilesForAccessibleTenant'
     */
    @Test
    public void assignedProfilesForAccessibleTenantTest() {
        // TODO: test assignedProfilesForAccessibleTenant
    }

}
