/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FailedLocalTenantProfileRevokeDTO;
import com.konfigthis.client.model.SuccessfulLocalTenantProfileAssignmentDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocalTenantProfileRevokeResponseDTO
 */
public class LocalTenantProfileRevokeResponseDTOTest {
    private final LocalTenantProfileRevokeResponseDTO model = new LocalTenantProfileRevokeResponseDTO();

    /**
     * Model tests for LocalTenantProfileRevokeResponseDTO
     */
    @Test
    public void testLocalTenantProfileRevokeResponseDTO() {
        // TODO: test LocalTenantProfileRevokeResponseDTO
    }

    /**
     * Test the property 'failed'
     */
    @Test
    public void failedTest() {
        // TODO: test failed
    }

    /**
     * Test the property 'succeeded'
     */
    @Test
    public void succeededTest() {
        // TODO: test succeeded
    }

}
