/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for LocalTenantProfileAssignmentRequestDTO
 */
public class LocalTenantProfileAssignmentRequestDTOTest {
    private final LocalTenantProfileAssignmentRequestDTO model = new LocalTenantProfileAssignmentRequestDTO();

    /**
     * Model tests for LocalTenantProfileAssignmentRequestDTO
     */
    @Test
    public void testLocalTenantProfileAssignmentRequestDTO() {
        // TODO: test LocalTenantProfileAssignmentRequestDTO
    }

    /**
     * Test the property 'targetUserIds'
     */
    @Test
    public void targetUserIdsTest() {
        // TODO: test targetUserIds
    }

    /**
     * Test the property 'validityStartTime'
     */
    @Test
    public void validityStartTimeTest() {
        // TODO: test validityStartTime
    }

    /**
     * Test the property 'validityEndTime'
     */
    @Test
    public void validityEndTimeTest() {
        // TODO: test validityEndTime
    }

}
