/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ProfileGetAPIResponseDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProfilesGetAPIResponseDTO
 */
public class ProfilesGetAPIResponseDTOTest {
    private final ProfilesGetAPIResponseDTO model = new ProfilesGetAPIResponseDTO();

    /**
     * Model tests for ProfilesGetAPIResponseDTO
     */
    @Test
    public void testProfilesGetAPIResponseDTO() {
        // TODO: test ProfilesGetAPIResponseDTO
    }

    /**
     * Test the property 'profiles'
     */
    @Test
    public void profilesTest() {
        // TODO: test profiles
    }

}
