/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ProfileAssignedForAccessibleTenantDTO
 */
public class ProfileAssignedForAccessibleTenantDTOTest {
    private final ProfileAssignedForAccessibleTenantDTO model = new ProfileAssignedForAccessibleTenantDTO();

    /**
     * Model tests for ProfileAssignedForAccessibleTenantDTO
     */
    @Test
    public void testProfileAssignedForAccessibleTenantDTO() {
        // TODO: test ProfileAssignedForAccessibleTenantDTO
    }

    /**
     * Test the property 'profileId'
     */
    @Test
    public void profileIdTest() {
        // TODO: test profileId
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'forAllChildren'
     */
    @Test
    public void forAllChildrenTest() {
        // TODO: test forAllChildren
    }

    /**
     * Test the property 'validityStartTime'
     */
    @Test
    public void validityStartTimeTest() {
        // TODO: test validityStartTime
    }

    /**
     * Test the property 'validityEndTime'
     */
    @Test
    public void validityEndTimeTest() {
        // TODO: test validityEndTime
    }

}
