/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReducedErrorDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReducedTenantCodeErrorDTO
 */
public class ReducedTenantCodeErrorDTOTest {
    private final ReducedTenantCodeErrorDTO model = new ReducedTenantCodeErrorDTO();

    /**
     * Model tests for ReducedTenantCodeErrorDTO
     */
    @Test
    public void testReducedTenantCodeErrorDTO() {
        // TODO: test ReducedTenantCodeErrorDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'forAllChildren'
     */
    @Test
    public void forAllChildrenTest() {
        // TODO: test forAllChildren
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
