/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for SuccessfulLocalTenantProfileAssignmentDTO
 */
public class SuccessfulLocalTenantProfileAssignmentDTOTest {
    private final SuccessfulLocalTenantProfileAssignmentDTO model = new SuccessfulLocalTenantProfileAssignmentDTO();

    /**
     * Model tests for SuccessfulLocalTenantProfileAssignmentDTO
     */
    @Test
    public void testSuccessfulLocalTenantProfileAssignmentDTO() {
        // TODO: test SuccessfulLocalTenantProfileAssignmentDTO
    }

    /**
     * Test the property 'userId'
     */
    @Test
    public void userIdTest() {
        // TODO: test userId
    }

}
