/*
 * Visier Profile Management APIs
 * Visier APIs for managing the profiles assigned to users
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * SuccessfulAccessibleTenantProfileAssignmentDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class SuccessfulAccessibleTenantProfileAssignmentDTO {
  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_TENANT_CODE = "tenantCode";
  @SerializedName(SERIALIZED_NAME_TENANT_CODE)
  private String tenantCode;

  public static final String SERIALIZED_NAME_FOR_ALL_CHILDREN = "forAllChildren";
  @SerializedName(SERIALIZED_NAME_FOR_ALL_CHILDREN)
  private Boolean forAllChildren;

  public SuccessfulAccessibleTenantProfileAssignmentDTO() {
  }

  public SuccessfulAccessibleTenantProfileAssignmentDTO userId(String userId) {
    
    
    
    
    this.userId = userId;
    return this;
  }

   /**
   * The user ID.
   * @return userId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user ID.")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    
    
    
    this.userId = userId;
  }


  public SuccessfulAccessibleTenantProfileAssignmentDTO tenantCode(String tenantCode) {
    
    
    
    
    this.tenantCode = tenantCode;
    return this;
  }

   /**
   * The tenant code.
   * @return tenantCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tenant code.")

  public String getTenantCode() {
    return tenantCode;
  }


  public void setTenantCode(String tenantCode) {
    
    
    
    this.tenantCode = tenantCode;
  }


  public SuccessfulAccessibleTenantProfileAssignmentDTO forAllChildren(Boolean forAllChildren) {
    
    
    
    
    this.forAllChildren = forAllChildren;
    return this;
  }

   /**
   * If true, the target assignment is for all analytic tenants.
   * @return forAllChildren
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If true, the target assignment is for all analytic tenants.")

  public Boolean getForAllChildren() {
    return forAllChildren;
  }


  public void setForAllChildren(Boolean forAllChildren) {
    
    
    
    this.forAllChildren = forAllChildren;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the SuccessfulAccessibleTenantProfileAssignmentDTO instance itself
   */
  public SuccessfulAccessibleTenantProfileAssignmentDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuccessfulAccessibleTenantProfileAssignmentDTO successfulAccessibleTenantProfileAssignmentDTO = (SuccessfulAccessibleTenantProfileAssignmentDTO) o;
    return Objects.equals(this.userId, successfulAccessibleTenantProfileAssignmentDTO.userId) &&
        Objects.equals(this.tenantCode, successfulAccessibleTenantProfileAssignmentDTO.tenantCode) &&
        Objects.equals(this.forAllChildren, successfulAccessibleTenantProfileAssignmentDTO.forAllChildren)&&
        Objects.equals(this.additionalProperties, successfulAccessibleTenantProfileAssignmentDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, tenantCode, forAllChildren, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuccessfulAccessibleTenantProfileAssignmentDTO {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    tenantCode: ").append(toIndentedString(tenantCode)).append("\n");
    sb.append("    forAllChildren: ").append(toIndentedString(forAllChildren)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("userId");
    openapiFields.add("tenantCode");
    openapiFields.add("forAllChildren");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to SuccessfulAccessibleTenantProfileAssignmentDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!SuccessfulAccessibleTenantProfileAssignmentDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in SuccessfulAccessibleTenantProfileAssignmentDTO is not found in the empty JSON string", SuccessfulAccessibleTenantProfileAssignmentDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("userId") != null && !jsonObj.get("userId").isJsonNull()) && !jsonObj.get("userId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userId").toString()));
      }
      if ((jsonObj.get("tenantCode") != null && !jsonObj.get("tenantCode").isJsonNull()) && !jsonObj.get("tenantCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantCode").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SuccessfulAccessibleTenantProfileAssignmentDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SuccessfulAccessibleTenantProfileAssignmentDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SuccessfulAccessibleTenantProfileAssignmentDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SuccessfulAccessibleTenantProfileAssignmentDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<SuccessfulAccessibleTenantProfileAssignmentDTO>() {
           @Override
           public void write(JsonWriter out, SuccessfulAccessibleTenantProfileAssignmentDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public SuccessfulAccessibleTenantProfileAssignmentDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             SuccessfulAccessibleTenantProfileAssignmentDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of SuccessfulAccessibleTenantProfileAssignmentDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of SuccessfulAccessibleTenantProfileAssignmentDTO
  * @throws IOException if the JSON string is invalid with respect to SuccessfulAccessibleTenantProfileAssignmentDTO
  */
  public static SuccessfulAccessibleTenantProfileAssignmentDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SuccessfulAccessibleTenantProfileAssignmentDTO.class);
  }

 /**
  * Convert an instance of SuccessfulAccessibleTenantProfileAssignmentDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

